book:
    title:            "Document Grid 1.0 Reference Manual"
    author:           "Anakeen Labs &lt;labs@anakeen.com&gt;"
    edition:          "1"
    language:         en
    publication_date: ~

    generator: { name: easybook, version: 4.8 }

    contents:
        # available content types: acknowledgement, afterword, appendix, author,
        # chapter, conclusion, cover, dedication, edition, epilogue, foreword,
        # glossary, introduction, license, lof (list of figures), lot (list of
        # tables), part, preface, prologue, title, toc (table of contents)
        - { element: cover }
        - { element: license, content: licence.md }
        - { element: author, content: author.md }
        - { element: toc   }
        - { element: chapter, number:  1, content: introduction.md }
        - { element: chapter, number:  2, content: mode-emploi.md }
        - { element: chapter, number:  3, content: criteres.md }
        - { element: chapter, number:  4, content: search-criteria-integration.md }
        - { element: chapter, number:  5, content: css.md }
        - { element: chapter, number:  6, content: php.md }
        - { element: chapter, number:  7, content: fonctionnement.md }
        - { element: chapter, number:  8, content: test.md }
        - { element: glossary }
        - { element: lof   }
        - { element: lot   }
        - { element: appendix   }

    editions:

        web:
            format:         html
            highlight_code: true
            include_styles: true
            labels:         []
            theme:          anakeen
            toc:
                deep:       3
                elements:   ["figure", "table"]

        website:
            extends:        web
            format:         html_chunked
            highlight_code: true

        ebook:
            format:         epub
            highlight_code: false
            include_styles: true
            labels:         ['appendix', 'chapter']
            toc:
                deep:       1
                elements:   ["appendix", "chapter"]

        print:
            format:         pdf
            include_styles: true
            highlight_code: true
            isbn:           ~
            labels:         ['figure', 'chapter']
            margin:
                top:        25mm
                bottom:     25mm
                inner:      30mm
                outter:     20mm
            page_size:      A4
            toc:
                deep:       2
                elements:   ["chapter"]
            two_sided:      true